/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyMintableToken__factory } from "./MyMintableToken__factory";
export { MyStrictToken__factory } from "./MyStrictToken__factory";
