/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MyMintableToken } from "./MyMintableToken";
export type { MyStrictToken } from "./MyStrictToken";
